version: '3.1'
services:
  stats-service:
    build: statistic-service/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistic_ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:15.3-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - stats-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=statistic_ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://localhost:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - EWM_STAT_SERVICE_URL=http://stats-service:9090
      - EWM_MAIN_NAME=main-service

  ewm-db:
    image: postgres:15.3-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    volumes:
      - ewm-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  stats-db:
  ewm-db: