version: '3.1'
services:
  stats-server:
    build: ./statistic-service/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
      - "5005:5005"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistic_ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root



  stats-db:
    image: postgres:15.3-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - stats-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=statistic_ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main-service
    image: ewm-server
    container_name: ewm-container
    ports:
      - "8080:8080"
      - "5006:5005"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://localhost:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005


  ewm-db:
    image: postgres:15.3-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    volumes:
      - ewm-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  stats-db:
  ewm-db: